objects/Bundled_UserStory__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_Story_Bundle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Story Bundle</label>
        <referenceTo>User_Story_Bundle__c</referenceTo>
        <relationshipName>Bundles_UserStories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User_Story__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Story</label>
        <referenceTo>User_Story__c</referenceTo>
        <relationshipName>Artifacts_UserStories</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Bundled User Story</label>
    <nameField>
        <displayFormat>BUSB-{0000000}</displayFormat>
        <label>Bundled User Story Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bundled_UserStories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Deployment_Flow__c.object
<CustomObject>
    <label>Pipeline</label>
    <nameField>
        <label>Pipeline Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pipelines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Environment__c.object
<CustomObject>
    <label>Environment</label>
    <nameField>
        <label>Environment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Environments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Git_Org_Commit__c.object
<CustomObject>
    <description>This object stores the individual commits to a Git repository executed by Copado Deployer.</description>
    <fields>
        <fullName>Git_Operation__c</fullName>
        <description>The Git operation executed by the Copado.</description>
        <inlineHelpText>The Git operation executed by the Copado.</inlineHelpText>
        <label>Git Operation</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Commit Files</fullName>
                    <default>true</default>
                    <label>Commit Files</label>
                </value>
                <value>
                    <fullName>Destructive Changes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The status of the commit. This value is updating automatically by Copado.</description>
        <inlineHelpText>The status of the commit. This value is updating automatically by Copado.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>No changes</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
                <value>
                    <fullName>Commit undone</fullName>
                </value>
                <value>
                    <fullName>Commit not in branch</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Snapshot Commit</label>
    <nameField>
        <displayFormat>Cmt-{0000}</displayFormat>
        <label>Commit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Snapshot Commits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Project__c.object
<CustomObject>
    <description>Overall object for capturing the project details.</description>
    <fields>
        <fullName>Deployment_Flow__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>If working with Copado Change Management, the Project must be linked to a Pipeline.</inlineHelpText>
        <label>Pipeline</label>
        <referenceTo>Deployment_Flow__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Planned</fullName>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Release__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Releases</relationshipLabel>
        <relationshipName>Releases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Planned</fullName>
                </value>
                <value>
                    <fullName>Released</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User_Story__c.object
<CustomObject>
    <description>Agile form of requirements gathering</description>
    <fields>
        <fullName>Environment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Current environment of the User Story. This value is added automatically by Copado based on the selected Org Credential.</description>
        <inlineHelpText>Current environment of the User Story. This value is added automatically by Copado based on the selected Org Credential.</inlineHelpText>
        <label>Environment</label>
        <referenceTo>Environment__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Project where the User Story belongs.</description>
        <inlineHelpText>Project where the User Story belongs.</inlineHelpText>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Release__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product version or release where this User Story will be released.</description>
        <inlineHelpText>Product version or release where this User Story will be released.</inlineHelpText>
        <label>Release</label>
        <referenceTo>Release__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Current status of the implementation of the User Story.</description>
        <inlineHelpText>Current status of the implementation of the User Story.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Backlog</fullName>
                </value>
                <value>
                    <fullName>Backburner</fullName>
                </value>
                <value>
                    <fullName>Awaiting Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Ready for testing</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>User Story Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User_Story_Bundle__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_Story__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Story</label>
        <referenceTo>User_Story__c</referenceTo>
        <relationshipLabel>User Story Bundles</relationshipLabel>
        <relationshipName>User_Story_Bundles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Story Bundle</label>
    <nameField>
        <displayFormat>USB-{0000000}</displayFormat>
        <label>User Story Bundle Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Story Bundles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User_Story_Commit__c.object
<CustomObject>
    <fields>
        <fullName>Snapshot_Commit__c</fullName>
        <label>Snapshot Commit</label>
        <referenceTo>Git_Org_Commit__c</referenceTo>
        <relationshipLabel>User Story Commits</relationshipLabel>
        <relationshipName>User_Story_Commits</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User_Story__c</fullName>
        <label>User Story</label>
        <referenceTo>User_Story__c</referenceTo>
        <relationshipLabel>User Story Commits</relationshipLabel>
        <relationshipName>User_Story_Commits</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>User Story Commit</label>
    <nameField>
        <label>US Commit</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Story Commits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/UserStoryBundleCtrl.cls
public with sharing class UserStoryBundleCtrl {
    public String stories { get; private set; }
    public String recordId { get; set; }
    private static Set<String> allMetadataNames = new Set<String>();

    // CONSTRUCTOR
    public UserStoryBundleCtrl(ApexPages.StandardSetController ctrl) {
        stories = JSON.serialize(selectedRecordIds(ctrl));
    }

    // PUBLIC
    @AuraEnabled(cacheable=true)
    public static List<User_Story__c> selectedStories(List<String> ids) {
        try {
            return new UserStoriesSelector().byIds(new Set<Id>((List<Id>) ids));
        } catch (Exception ex) {
            throw new AuraHandledException(ex.getMessage());
        }
    }

    @AuraEnabled(cacheable=true)
    public static List<MetaDataItem> getAllMetadata(List<String> ids, List<String> operations) {
        return metadataItems(attachments(ids, operations));
    }

    @AuraEnabled
    public static String createBundleRecords(
        User_Story_Bundle__c bundle,
        List<User_Story__c> stories,
        List<MetaDataItem> metadata,
        List<MetaDataItem> fullProfiles,
        List<MetaDataItem> destructiveChanges
    ) {
        List<String> validationErrors = new UserStoryBundleValidator(stories, metadata, fullProfiles, destructiveChanges).execute();
        if (!validationErrors.isEmpty()) {
            throw createAuraException(String.join(validationErrors, ','));
        }

        User_Story_Bundle__c result = new User_Story_Bundle__c();
        try {
            result = (User_Story_Bundle__c) Utilities.Secure_DML(bundle, Utilities.DML_Action.INS, Schema.SObjectType.User_Story_Bundle__c);
            createJunctionRecords(result, stories);
            createAttachments(result, stories, metadata, fullProfiles, destructiveChanges);
        } catch (Exception ex) {
            throw createAuraException(ex.getMessage());
        }
        return result.Id;
    }

    public Pagereference navigate() {
        PageReference result = new ApexPages.Action('{!List}').invoke();
        if (String.isNotBlank(recordId)) {
            result = new ApexPages.StandardController(new User_Story_Bundle__c(Id = recordId)).view();
            result.setRedirect(true);
        }
        return result;
    }

    // PRIVATE

    private static AuraHandledException createAuraException(String message) {
        AuraHandledException result = new AuraHandledException(message);
        result.setMessage(message);

        return result;
    }

    private Set<Id> selectedRecordIds(ApexPages.StandardSetController ctrl) {
        Map<Id, User_Story__c> selected = new Map<Id, User_Story__c>((List<User_Story__c>) ctrl.getSelected());
        return selected.keySet();
    }

    private static void createJunctionRecords(User_Story_Bundle__c bundle, List<User_Story__c> stories) {
        List<Bundled_UserStory__c> junctions = new List<Bundled_UserStory__c>();
        for (User_Story__c item : stories) {
            junctions.add(new Bundled_UserStory__c(User_Story__c = item.Id, User_Story_Bundle__c = bundle.Id));
        }
        Utilities.Secure_DML(junctions, Utilities.DML_Action.INS, Schema.SObjectType.Bundled_UserStory__c);
    }

    private static void createAttachments(
        User_Story_Bundle__c bundle,
        List<User_Story__c> stories,
        List<MetaDataItem> metadata,
        List<MetaDataItem> fullProfiles,
        List<MetaDataItem> destructiveChanges
    ) {
        List<Attachment> bundleAttachments = new List<Attachment>();

        if (!metadata.isEmpty()) {
            bundleAttachments.add(createAttachment(bundle, 'Metadata', metadata));
        }

        if (!fullProfiles.isEmpty()) {
            bundleAttachments.add(createAttachment(bundle, 'Full Profiles & Permission Sets', fullProfiles));
        }

        if (!destructiveChanges.isEmpty()) {
            bundleAttachments.add(createAttachment(bundle, 'Destructive Changes', destructiveChanges));
        }

        List<MetaDataItem> testClasses = testOnlyAttachment(new Map<Id, User_Story__c>(stories).keySet());
        if (!testClasses.isEmpty()) {
            bundleAttachments.add(createAttachment(bundle, 'Test Classes', testClasses));
        }

        insert bundleAttachments;
    }

    private static Attachment createAttachment(User_Story_Bundle__c bundle, String attachmentName, List<MetaDataItem> metadataItems) {
        return new Attachment(ParentId = bundle.Id, Name = attachmentName, Body = Blob.valueOf(JSON.serialize(metadataItems)));
    }

    private static List<MetaDataItem> testOnlyAttachment(Set<Id> storyIds) {
        Map<String, MetaDataItem> result = new Map<String, MetaDataItem>();
        for (Attachment record : new AttachmentsSelector().byParentIdAndName(storyIds, new Set<String>{ 'Test Classes' })) {
            // Merge the metadata to the result set.
            // Also checks if any class checked as Test only is commited, then that class will be removed from 'Test Classes' Attachment
            for (MetaDataItem metadata : metadataItems(record)) {
                if (!result.containsKey(metadata.n) && !allMetadataNames.contains(metadata.n)) {
                    result.put(metadata.n, metadata);
                }
            }
        }
        return result.values();
    }

    private static List<Attachment> attachments(List<String> ids, List<String> operations) {
        List<Attachment> result = new List<Attachment>();
        try {
            result = [
                SELECT Id, Body
                FROM Attachment
                WHERE
                    Name IN ('Metadata', 'Git Deletion')
                    AND ParentId IN (
                        SELECT Snapshot_Commit__c
                        FROM User_Story_Commit__c
                        WHERE
                            User_Story__r.Id IN :ids
                            AND Snapshot_Commit__r.Git_Operation__c = :operations
                            AND Snapshot_Commit__r.Status__c = 'Complete'
                    )
                WITH SECURITY_ENFORCED
                ORDER BY CreatedDate DESC
            ];
        } catch (System.QueryException ex) {
            throw new AuraHandledException(ex.getMessage());
        }
        return result;
    }

    private static List<MetaDataItem> metadataItems(List<Attachment> attachments) {
        Map<String, MetaDataItem> result = new Map<String, MetaDataItem>();
        for (Attachment record : attachments) {
            for (MetaDataItem metadata : metadataItems(record)) {
                String key = metadata.t + '.' + metadata.n;
                if (!result.containsKey(key)) {
                    metadata.s = true;
                    result.put(key, metadata);
                    allMetadataNames.add(metadata.n);
                } else {
                    // If it exists, check if it has metadata.r = false, and ensure it's also false in result
                    // This is to ensure if it is not retrieve-only at least once, it must be not retrieve only.
                    if (metadata.r == null || !metadata.r) {
                        result.get(key).r = false;
                    }
                }
            }
        }
        return result.values();
    }

    private static List<MetaDataItem> metadataItems(Attachment record) {
        List<MetaDataItem> result = new List<MetaDataItem>();
        try {
            result = (List<MetaDataItem>) JSON.deserialize(record.Body.toString(), List<MetaDataItem>.class);
        } catch (Exception ex) {
            throw new AuraHandledException('Not parsed data ' + ex.getMessage());
        }
        return result;
    }

    private class UserStoryBundleValidator {
        private List<User_Story__c> stories;
        private List<MetaDataItem> metadata;
        private List<MetaDataItem> fullProfiles;
        private List<MetaDataItem> destructiveChanges;

        UserStoryBundleValidator(
            List<User_Story__c> stories,
            List<MetaDataItem> metadata,
            List<MetaDataItem> fullProfiles,
            List<MetaDataItem> destructiveChanges
        ) {
            this.stories = stories;
            this.metadata = metadata;
            this.fullProfiles = fullProfiles;
            this.destructiveChanges = destructiveChanges;
        }

        public List<String> execute() {
            List<String> result = new List<String>();

            if (stories.isEmpty() || stories.size() == 1) {
                result.add(System.Label.USB_WARNING_NO_US_SELECTED);
            } else if (metadata.isEmpty() && fullProfiles.isEmpty() && destructiveChanges.isEmpty()) {
                result.add(System.Label.USB_WARNING_NO_COMMITS);
            } else {
                if (differentEnvironmentsIn(stories)) {
                    result.add(System.Label.USB_WARNING_DIFFERENT_ENVIRONMENTS);
                }
                if (differentPipelinesIn(stories)) {
                    result.add(System.Label.USB_WARNING_DIFFERENT_PIPELINES);
                }
            }

            return result;
        }

        private Boolean differentEnvironmentsIn(List<User_Story__c> stories) {
            Boolean result = false;

            Id refEnvironment = stories.get(0).Environment__c;
            for (User_Story__c story : stories) {
                if (story.Environment__c != refEnvironment) {
                    result = true;
                    break;
                }
            }

            return result;
        }

        private Boolean differentPipelinesIn(List<User_Story__c> stories) {
            Boolean result = false;

            Id refPipeline = getPipelineRelatedTo(stories.get(0));
            for (User_Story__c story : stories) {
                if (getPipelineRelatedTo(story) != refPipeline) {
                    result = true;
                    break;
                }
            }

            return result;
        }

        private Id getPipelineRelatedTo(User_Story__c story) {
            Id result;

            if (story.Project__r.Deployment_Flow__c != null) {
                result = story.Project__r.Deployment_Flow__c;
            } else if (story.Release__r.Project__r.Deployment_Flow__c != null) {
                result = story.Release__r.Project__r.Deployment_Flow__c;
            }

            return result;
        }
    }
}