objects/Compliance_Rule__c.object
<CustomObject>
    <description>This object stores the compliance rule definition.</description>
    <fields>
        <fullName>Filter_Criteria__c</fullName>
        <inlineHelpText>Criteria filter query</inlineHelpText>
        <label>Filter Criteria</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Is_Valid__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Automatically updated by copado when saving managing criteria</inlineHelpText>
        <label>Is Valid</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Matching_Criteria__c</fullName>
        <inlineHelpText>Operator between Record Count Criteria and Record Count</inlineHelpText>
        <label>Matching Criteria</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Equals</fullName>
                </value>
                <value>
                    <fullName>Not Equals</fullName>
                </value>
                <value>
                    <fullName>Less Than</fullName>
                </value>
                <value>
                    <fullName>Less or Equal</fullName>
                </value>
                <value>
                    <fullName>Greater Than</fullName>
                </value>
                <value>
                    <fullName>Greater or Equal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Metadata_Type__c</fullName>
        <label>Metadata Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_Count_Criteria__c</fullName>
        <label>Record Count Criteria</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Number of groups</fullName>
                    <default>true</default>
                    <label>Number of groups</label>
                </value>
                <value>
                    <fullName>Number of files</fullName>
                    <isActive>false</isActive>
                    <label>Number of files</label>
                </value>
                <value>
                    <fullName>Number of properties</fullName>
                    <isActive>false</isActive>
                    <label>Number of properties</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Record_Count__c</fullName>
        <inlineHelpText>Number of returned values to assert.</inlineHelpText>
        <label>Record Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Compliance Rule</label>
    <nameField>
        <label>Compliance Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compliance Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Compliance_Rule_Criteria__c.object
<CustomObject>
    <description>This object stores the individual evaluation criteria that make up the compliance rule.</description>
    <fields>
        <fullName>Compliance_Rule__c</fullName>
        <label>Compliance Rule</label>
        <referenceTo>Compliance_Rule__c</referenceTo>
        <relationshipLabel>Compliance Rule Criteria</relationshipLabel>
        <relationshipName>Compliance_Rule_Criteria</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Compliance Rule Criteria</label>
    <nameField>
        <displayFormat>RC-{000000}</displayFormat>
        <label>Compliance Rule Criteria Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compliance Rule Criterias</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ComplianceRuleManagerCtrl.cls
public with sharing class ComplianceRuleManagerCtrl {
    // PUBLIC

    @AuraEnabled
    public static String getComplianceFileFromBackend() {
        HttpRequest request = new HttpRequest();
        DeployAPI.setAuthHeaders(request);
        request.setTimeout(30000);
        request.setHeader('Accept', 'application/json');
        request.setEndpoint(Settings.server_url + '/json/v1/complianceMetadata');
        request.setMethod('GET');

        HttpResponse result = new Http().send(request);
        return result.getBody();
    }

    @AuraEnabled
    public static void deleteCriterias(List<Compliance_Rule_Criteria__c> criterias) {
        try {
            Utilities.Secure_DML(criterias, Utilities.DML_Action.DEL, Schema.SObjectType.Compliance_Rule_Criteria__c);
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static void saveCriterias(List<Compliance_Rule_Criteria__c> criteria, String criteriaLogic, String metadataType) {
        try {
            Savepoint sp = Database.setSavepoint();
            if (!criteria.isEmpty()) {
                Utilities.Secure_DML(criteria, Utilities.DML_Action.UPS, Schema.SObjectType.Compliance_Rule_Criteria__c);

                Id ruleId = criteria.get(0).Compliance_Rule__c;

                Compliance_Rule__c rule = new ComplianceRulesSelector().byId(new Set<Id>{ ruleId }).get(0);
                rule.Metadata_Type__c = metadataType;
                rule.Filter_Criteria__c = parseLogic(criteriaLogic, ruleId);
                // @TODO: Add validations in US-0019285
                rule.Is_Valid__c = true;
                // @TODO: To be removed when backend deletes it
                rule.Record_Count_Criteria__c = 'Number of groups';
                rule.Matching_Criteria__c = 'Greater or Equal';
                rule.Record_Count__c = 1;

                Utilities.Secure_DML(rule, Utilities.DML_Action.UPD, Schema.SObjectType.Compliance_Rule__c);
            }
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static List<Compliance_Rule_Criteria__c> criteriasOfRule(Id ruleId) {
        return new ComplianceRuleCriteriaSelector().byComplianceRuleId(new Set<Id>{ ruleId });
    }

    @AuraEnabled
    public static Boolean hasComplianceRuleFLS() {
        Set<DescribeFieldResult> fields = new Set<DescribeFieldResult>{
            Schema.SObjectType.Compliance_Rule__c.fields.Metadata_Type__c,
            Schema.SObjectType.Compliance_Rule__c.fields.Filter_Criteria__c,
            Schema.SObjectType.Compliance_Rule__c.fields.Is_Valid__c
        };

        try {
            return isAccessible(fields);
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    // PRIVATE

    private static String parseLogic(String criteriaLogic, Id ruleId) {
        String result = criteriaLogic;    

        Integer criteriaCount = criteriaLogic.split('AND|OR').size();
        Map<Decimal, Compliance_Rule_Criteria__c> criteriaByOrder = getCriteriaByOrder(criteriasOfRule(ruleId));

        for (Integer i = 1; i <= criteriaCount; i++) {
            result = result.replaceFirst(String.valueOf(i), '<' + String.valueOf(i) + '>');
        }

        for (Integer i = 1; i <= criteriaCount; i++) {
            result = result.replaceFirst('<' + String.valueOf(i) + '>', criteriaByOrder.get(i).Name);
        }

        return result;
    }

    private static Map<Decimal, Compliance_Rule_Criteria__c> getCriteriaByOrder(List<Compliance_Rule_Criteria__c> criteriaList) {
        Map<Decimal, Compliance_Rule_Criteria__c> result = new Map<Decimal, Compliance_Rule_Criteria__c>();

        for (Compliance_Rule_Criteria__c criteria : criteriaList) {
            result.put(criteria.Order__c, criteria);
        }

        return result;
    }

    private static Boolean isAccessible(Set<DescribeFieldResult> fields) {
        Boolean result = true;

        for (DescribeFieldResult field : fields) {
            if (!field.isAccessible()) {
                result = false;
                break;
            }
        }

        return result;
    }
}