objects/Data_Set__c.object
<CustomObject>
    <description>Stores a set of file attachments with record data from a Data Template.</description>
    <fields>
        <fullName>Data_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Related Data Template record that defines related objects and their relationships for the attachments of this Data Set.</description>
        <label>Data Template</label>
        <referenceTo>Data_Template__c</referenceTo>
        <relationshipLabel>Data Sets</relationshipLabel>
        <relationshipName>Data_Sets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Data Set</label>
    <nameField>
        <label>Data Set Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Data Sets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Data_Template__c.object
<CustomObject>
    <label>Data Template</label>
    <nameField>
        <label>Data Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Data Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Deployment__c.object
<CustomObject>
    <fields>
        <fullName>From_Org__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Source Org</label>
        <referenceTo>Org__c</referenceTo>
        <relationshipLabel>Deployments (From Org)</relationshipLabel>
        <relationshipName>Deployments_From_Org</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Deployment</label>
    <nameField>
        <label>Deployment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deployments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Destination_Org__c.object
<CustomObject>
    <fields>
        <fullName>Deployment__c</fullName>
        <label>Deployment</label>
        <referenceTo>Deployment__c</referenceTo>
        <relationshipLabel>Destination Orgs</relationshipLabel>
        <relationshipName>Destination_Orgs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>To_Org__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>To Org</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Org__c.CreatedById</field>
                <operation>equals</operation>
                <valueField>$User.Id</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Org__c</referenceTo>
        <relationshipLabel>Deployments To</relationshipLabel>
        <relationshipName>Deployments_to</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Destination Org</label>
    <nameField>
        <displayFormat>DO-{0000}</displayFormat>
        <label>Destination Org Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Destination Orgs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Step__c.object
<CustomObject>
    <fields>
        <fullName>Deployment__c</fullName>
        <label>Deployment</label>
        <referenceTo>Deployment__c</referenceTo>
        <relationshipLabel>Steps</relationshipLabel>
        <relationshipName>Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>dataJson__c</fullName>
        <description>If the step type is &quot;data&quot;  this should contains the json defining the query. 
In production this field should be HIDDEN</description>
        <label>dataJson</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Step</label>
    <nameField>
        <label>Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/DataStepValidator.cls
public with sharing class DataStepValidator {
    private Id stepId;

    public DataStepValidator(Id stepId) {
        this.stepId = stepId;
    }

    public void validate() {
        Id sourceOrg = getDeploymentSourceOrg();
        List<Id> destinationOrgs = getDeploymentDestinationOrgs();
        List<Id> dataTemplateIds = getDataTemplates();

        DataTemplateDeploymentValidator validator = new DataTemplateDeploymentValidator(dataTemplateIds, sourceOrg, destinationOrgs);
        DataTemplateDeploymentValidationResult result = validator.validate();
        DataStepValidatorResultHandler resultHandler = new DataStepValidatorResultHandler(this.stepId);
        resultHandler.handle(result);
    }

    private Step__c getStep() {
        List<Step__c> steps = new StepsSelector().byId(new List<Id>{ this.stepId });
        return !steps.isEmpty() ? steps[0] : null;
    }

    private Id getDeploymentSourceOrg() {
        Step__c step = getStep();
        return step.Deployment__r.From_Org__c;
    }

    private List<Id> getDeploymentDestinationOrgs() {
        Step__c step = getStep();
        List<Destination_Org__c> destinationOrgs = new DestinationOrgsSelector().byDeploymentId(new List<Id>{ step.Deployment__c });
        List<Id> destinationOrgIds = new List<Id>();
        for (Destination_Org__c destinationOrg : destinationOrgs) {
            destinationOrgIds.add(destinationOrg.To_Org__c);
        }
        return destinationOrgIds;
    }

    private List<Id> getDataTemplates() {
        List<Id> dataTemplateIds = new List<Id>();
        Id dataTemplateId = getDataTemplate();
        dataTemplateIds.add(dataTemplateId);
        dataTemplateIds.addAll(getRelatedDataTemplates(dataTemplateId));
        return dataTemplateIds;
    }

    private Id getDataTemplate() {
        DataStepData stepData = getStepData();

        Id dataTemplateId = getDataTemplateFromStepData(stepData);

        return dataTemplateId;
    }

    private DataStepData getStepData() {
        Step__c step = getStep();
        DataStepData stepData = (DataStepData) JSON.deserialize(step.dataJSON__c, DataStepData.class);
        return stepData;
    }

    private Id getDataTemplateFromStepData(DataStepData stepData) {
        Id dataTemplateId;
        if (String.isNotBlank(stepData.dataTemplateId)) {
            dataTemplateId = stepData.dataTemplateId;
        } else if (stepData.source != null) {
            switch on stepData.source.type {
                when DATASET {
                    List<Data_Set__c> dataSets = new DataSetsSelector().byId(new Set<Id>{ stepData.source.id });
                    if (!dataSets.isEmpty()) {
                        Data_Set__c dataSet = dataSets[0];
                        dataTemplateId = dataSet.Data_Template__c;
                    }
                }
            }
        }
        return dataTemplateId;
    }

    private List<Id> getRelatedDataTemplates(Id dataTemplateId) {
        List<Id> dataTemplateIds = new List<Id>();

        List<Attachment> attachments = new AttachmentsSelector()
            .byParentIdAndName(new Set<Id>{ dataTemplateId }, new Set<String>{ DataTemplateDetail.ATTACHMENT_NAME });
        for (Attachment attachment : attachments) {
            DataTemplateDetail templateDetail = (DataTemplateDetail) JSON.deserialize(attachment.Body.toString(), DataTemplateDetail.class);
            dataTemplateIds.addAll(getRelationTemplateDetailsIds(templateDetail.parentObjectsReferenceList));
            dataTemplateIds.addAll(getRelationTemplateDetailsIds(templateDetail.childrenObjectsReferenceList));
        }

        return dataTemplateIds;
    }

    private List<Id> getRelationTemplateDetailsIds(List<DataTemplateDetail.RelationTemplateDetails> relationTemplateDetails) {
        List<Id> ids = new List<Id>();
        for (DataTemplateDetail.RelationTemplateDetails relationTemplateDetail : relationTemplateDetails) {
            String dataTemplateId = relationTemplateDetail.templateId;
            if (String.isNotBlank(dataTemplateId) && dataTemplateId instanceof Id) {
                ids.add(dataTemplateId);
            }
        }
        return ids;
    }
}