objects/Data_Set__c.object
<CustomObject>
    <description>Stores a set of file attachments with record data from a Data Template.</description>
    <fields>
        <fullName>Last_Generated_Date__c</fullName>
        <description>Date and time of the last time the data set was generated (i.e. attached files were updated).</description>
        <inlineHelpText>This date is automatically updated by Copado when generating the data set CSV files from a source environment. Update this value when generating the CSV files from an external database or process.</inlineHelpText>
        <label>Last Generated Date</label>
        <type>DateTime</type>
    </fields>
    <label>Data Set</label>
    <nameField>
        <label>Data Set Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Data Sets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Deployment__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <inlineHelpText>When this need to be deployed</inlineHelpText>
        <label>Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Deployment_command_sent__c</fullName>
        <label>Deployment command sent</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>From_Org__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Source Org</label>
        <referenceTo>Org__c</referenceTo>
        <relationshipLabel>Deployments (From Org)</relationshipLabel>
        <relationshipName>Deployments_From_Org</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
                <value>
                    <fullName>Completed Successfully</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Completed with Errors</fullName>
                </value>
                <value>
                    <fullName>Merge Conflict</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Deployment</label>
    <nameField>
        <label>Deployment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deployments</pluralLabel>
    <recordTypes>
        <fullName>Advanced_multi_step</fullName>
        <active>true</active>
        <description>Create multiple types of deployment steps. (Technical knowledge needed)</description>
        <label>Advanced (multi-step)</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Destination_Org__c.object
<CustomObject>
    <fields>
        <fullName>Deployment__c</fullName>
        <label>Deployment</label>
        <referenceTo>Deployment__c</referenceTo>
        <relationshipLabel>Destination Orgs</relationshipLabel>
        <relationshipName>Destination_Orgs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not started</fullName>
                    <default>true</default>
                    <label>Not started</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed Successfully</fullName>
                </value>
                <value>
                    <fullName>Completed with Errors</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>To_Org__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>To Org</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Org__c.CreatedById</field>
                <operation>equals</operation>
                <valueField>$User.Id</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Org__c</referenceTo>
        <relationshipLabel>Deployments To</relationshipLabel>
        <relationshipName>Deployments_to</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Destination Org</label>
    <nameField>
        <displayFormat>DO-{0000}</displayFormat>
        <label>Destination Org Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Destination Orgs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Org__c.object
<CustomObject>
    <fields>
        <fullName>SFDC_Org_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Organization Id for the Environment.</description>
        <externalId>true</externalId>
        <inlineHelpText>Organization Id for the Environment.</inlineHelpText>
        <label>SFDC Org ID</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Validated_Date__c</fullName>
        <description>Latest OAuth authentication validation date.</description>
        <inlineHelpText>Latest OAuth authentication validation date.</inlineHelpText>
        <label>Validated Date</label>
        <type>DateTime</type>
    </fields>
    <label>Org Credential</label>
    <nameField>
        <label>Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Org Credentials</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Step__c.object
<CustomObject>
    <fields>
        <fullName>Deployment__c</fullName>
        <label>Deployment</label>
        <referenceTo>Deployment__c</referenceTo>
        <relationshipLabel>Steps</relationshipLabel>
        <relationshipName>Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not started</fullName>
                    <default>true</default>
                    <label>Not started</label>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
                <value>
                    <fullName>Completed Successfully</fullName>
                </value>
                <value>
                    <fullName>Completed with Errors</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>MetaData</fullName>
                    <default>true</default>
                    <label>MetaData</label>
                </value>
                <value>
                    <fullName>Full Profiles</fullName>
                </value>
                <value>
                    <fullName>Full Permission Sets</fullName>
                </value>
                <value>
                    <fullName>Users</fullName>
                </value>
                <value>
                    <fullName>Translations</fullName>
                </value>
                <value>
                    <fullName>Data</fullName>
                </value>
                <value>
                    <fullName>Bulk Data</fullName>
                </value>
                <value>
                    <fullName>Data Template</fullName>
                </value>
                <value>
                    <fullName>Delete MetaData</fullName>
                </value>
                <value>
                    <fullName>Custom Settings</fullName>
                </value>
                <value>
                    <fullName>Apex</fullName>
                </value>
                <value>
                    <fullName>Git MetaData</fullName>
                </value>
                <value>
                    <fullName>URL Callout</fullName>
                </value>
                <value>
                    <fullName>Automation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>dataJson__c</fullName>
        <description>If the step type is &quot;data&quot;  this should contains the json defining the query. 
In production this field should be HIDDEN</description>
        <label>dataJson</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Step</label>
    <nameField>
        <label>Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/DataDeployer.cls
public with sharing class DataDeployer {
    private static final String ADVANCED_DEPLOYMENT_RECORD_TYPE_ID = Schema.SObjectType.Deployment__c.getRecordTypeInfosByDeveloperName()
        .get('Advanced_multi_step')
        .getRecordTypeId();
    private static final String DEPLOYMENT_NAME = 'Data Deploy';
    private static final String STEP_NAME = 'Step 1';
    private static final String DATA_TEMPLATE_TYPE = 'Data Template';
    private static final String SCHEDULED_STATUS = 'Scheduled';

    private DataDeployRequest deployRequest;

    private Deployment__c dataDeployment;

    private Id currentOrgCredential {
        get {
            if (currentOrgCredential == null) {
                String orgId = UserInfo.getOrganizationId() + '_' + UserInfo.getUserId();
                List<Org__c> orgs = [
                    SELECT Id
                    FROM Org__c
                    WHERE Validated_Date__c != NULL AND SFDC_Org_ID__c = :orgId
                    WITH SECURITY_ENFORCED
                    LIMIT 1
                ];
                if (orgs.isEmpty()) {
                    throw new DataDeployerException(Label.Error_Getting_Current_Org_Credential);
                }
                currentOrgCredential = orgs[0].Id;
            }
            return currentOrgCredential;
        }
        set;
    }

    public DataDeployer(DataDeployRequest deployRequest) {
        List<String> errors = validateRequest(deployRequest);
        if (!errors.isEmpty()) {
            throw new DataDeployerException(String.join(errors, ', '));
        }
        this.deployRequest = deployRequest;
    }

    public Id execute() {
        this.dataDeployment = createDeployment();

        createStep();

        if (this.deployRequest.getDeployNow() == true) {
            setDeploymentToScheduled();

            if (this.deployRequest.getDestinationType() == DataDeployRequest.Destination.DATASET) {
                setDataSetLastGeneratedDate();
            }

            deploy();
        }

        return this.dataDeployment.Id;
    }

    private List<String> validateRequest(DataDeployRequest request) {
        List<String> errors = new List<String>();
        if (request.getSourceType() == null) {
            errors.add(Label.Data_Source_Required);
        }
        if (request.getDestinationType() == null) {
            errors.add(Label.Data_Destination_Required);
        }
        if (request.getSourceType() == DataDeployRequest.Source.ENVIRONMENT && request.getDataTemplateId() == null) {
            errors.add(Label.Data_Template_Id_Required);
        }
        if (request.getSourceType() == DataDeployRequest.Source.DATASET && request.getSourceDataSetId() == null) {
            errors.add(Label.Source_Data_Set_Id_Required);
        }
        if (request.getSourceType() == DataDeployRequest.Source.BRANCH && request.getSourceBranchName() == null) {
            errors.add(Label.Source_Branch_Name_Required);
        }
        if (request.getDestinationType() == DataDeployRequest.Destination.DATASET && request.getDestinationDataSetId() == null) {
            errors.add(Label.Destination_Data_Set_Id_Required);
        }
        if (request.getDestinationType() == DataDeployRequest.Destination.BRANCH && request.getDestinationBranchName() == null) {
            errors.add(Label.Destination_Branch_Name_Required);
        }
        return errors;
    }

    private Deployment__c createDeployment() {
        Id sourceCrendentialId = this.deployRequest.getSourceCredentialId() != null
            ? this.deployRequest.getSourceCredentialId()
            : currentOrgCredential;

        Deployment__c dataDeployment = new Deployment__c(
            Name = DEPLOYMENT_NAME,
            From_Org__c = sourceCrendentialId,
            RecordTypeId = ADVANCED_DEPLOYMENT_RECORD_TYPE_ID
        );

        Utilities.Secure_DML(dataDeployment, Utilities.DML_Action.INS, Schema.SObjectType.Deployment__c);

        Id destinationCredentialId = this.deployRequest.getDestinationCredentialId() != null
            ? this.deployRequest.getDestinationCredentialId()
            : dataDeployment.From_Org__c;

        Destination_Org__c destinationOrg = new Destination_Org__c(Deployment__c = dataDeployment.Id, To_Org__c = destinationCredentialId);

        Utilities.Secure_DML(destinationOrg, Utilities.DML_Action.INS, Schema.SObjectType.Destination_Org__c);

        return dataDeployment;
    }

    private void createStep() {
        String dataJson = generateDataJson();

        String stepName = getStepName();

        Step__c dataTemplateStep = new Step__c(
            dataJson__c = dataJson,
            Deployment__c = this.dataDeployment.Id,
            Name = stepName,
            Type__c = DATA_TEMPLATE_TYPE
        );

        Utilities.Secure_DML(dataTemplateStep, Utilities.DML_Action.INS, Schema.SObjectType.Step__c);
    }

    private String generateDataJson() {
        DataStepData data = new DataStepData(this.deployRequest);
        return JSON.serialize(data, true);
    }

    private String getStepName() {
        String stepName = STEP_NAME;
        if (this.deployRequest.getDestinationType() == DataDeployRequest.Destination.DATASET) {
            List<Data_Set__c> dataSets = [
                SELECT Name
                FROM Data_Set__c
                WHERE Id = :this.deployRequest.getDestinationDataSetId()
                WITH SECURITY_ENFORCED
                LIMIT 1
            ];
            if (!dataSets.isEmpty()) {
                Data_Set__c destinationDataSet = dataSets[0];
                stepName = 'Generate ' + destinationDataSet.Name;
            }
        }
        return stepName;
    }

    private void setDeploymentToScheduled() {
        Deployment__c updatedDeployment = new Deployment__c(
            Id = this.dataDeployment.Id,
            Status__c = SCHEDULED_STATUS,
            Date__c = System.now(),
            Deployment_command_sent__c = null
        );

        Utilities.Secure_DML(updatedDeployment, Utilities.DML_Action.UPD, Schema.SObjectType.Deployment__c);
    }

    private void setDataSetLastGeneratedDate() {
        Data_Set__c updatedDataSet = new Data_Set__c(Id = this.deployRequest.getDestinationDataSetId(), Last_Generated_Date__c = System.now());

        Utilities.Secure_DML(updatedDataSet, Utilities.DML_Action.UPD, Schema.SObjectType.Data_Set__c);
    }

    private void deploy() {
        DeployAPI.deploy(new List<Id>{ this.dataDeployment.Id }, null);
    }

    public class DataDeployerException extends Exception {
    }
}