objects/Deployment__c.object
<CustomObject>
    <fields>
        <fullName>From_Org__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Source Org</label>
        <referenceTo>Org__c</referenceTo>
        <relationshipLabel>Deployments (From Org)</relationshipLabel>
        <relationshipName>Deployments_From_Org</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Deployment</label>
    <nameField>
        <label>Deployment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deployments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/DeploymentsSelector.cls
public with sharing class DeploymentsSelector extends fflib_SObjectSelector {
    public SObjectType getSObjectType() {
        return Deployment__c.sObjectType;
    }

    public List<SObjectField> getSObjectFieldList() {
        return new List<SObjectField>{ Deployment__c.Id, Deployment__c.Name, Deployment__c.From_Org__c };
    }

    public DeploymentsSelector() {
        this(true);
    }

    public DeploymentsSelector(Boolean enforceFLS) {
        super(false, true, enforceFLS);
    }

    public List<Deployment__c> byId(List<Id> recordIds) {
        return (List<Deployment__c>) byId(new Set<Id>(recordIds));
    }

    public List<Deployment__c> byId(Set<Id> recordIds) {
        return (List<Deployment__c>) selectSObjectsById(recordIds);
    }
}