objects/Deployment__c.object
<CustomObject>
    <label>Deployment</label>
    <nameField>
        <label>Deployment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deployments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Destination_Org__c.object
<CustomObject>
    <fields>
        <fullName>Deployment__c</fullName>
        <label>Deployment</label>
        <referenceTo>Deployment__c</referenceTo>
        <relationshipLabel>Destination Orgs</relationshipLabel>
        <relationshipName>Destination_Orgs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>To_Org__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>To Org</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Org__c.CreatedById</field>
                <operation>equals</operation>
                <valueField>$User.Id</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Org__c</referenceTo>
        <relationshipLabel>Deployments To</relationshipLabel>
        <relationshipName>Deployments_to</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Destination Org</label>
    <nameField>
        <displayFormat>DO-{0000}</displayFormat>
        <label>Destination Org Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Destination Orgs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/DestinationOrgsSelector.cls
public with sharing class DestinationOrgsSelector extends fflib_SObjectSelector {
    public SObjectType getSObjectType() {
        return Destination_Org__c.sObjectType;
    }

    public List<SObjectField> getSObjectFieldList() {
        return new List<SObjectField>{ Destination_Org__c.Id, Destination_Org__c.Deployment__c, Destination_Org__c.To_Org__c };
    }

    public DestinationOrgsSelector() {
        this(true);
    }

    public DestinationOrgsSelector(Boolean enforceFLS) {
        super(false, true, enforceFLS);
    }

    public List<Destination_Org__c> byId(List<Id> recordIds) {
        return (List<Destination_Org__c>) byId(new Set<Id>(recordIds));
    }

    public List<Destination_Org__c> byId(Set<Id> recordIds) {
        return (List<Destination_Org__c>) selectSObjectsById(recordIds);
    }

    public List<Destination_Org__c> byDeploymentId(List<Id> deploymentIds) {
        return (List<Destination_Org__c>) byDeploymentId(new Set<Id>(deploymentIds));
    }

    public List<Destination_Org__c> byDeploymentId(Set<Id> deploymentIds) {
        fflib_QueryFactory query = newQueryFactory().setCondition('Deployment__c IN :deploymentIds');

        fflib_SObjectSelector deploymentsSlector = new DeploymentsSelector();
        deploymentsSlector.configureQueryFactoryFields(query, 'Deployment__r');

        return (List<Destination_Org__c>) Database.query(query.toSOQL());
    }
}