objects/Org__c.object
<CustomObject>
    <fields>
        <fullName>Disable_Validation__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Checking this checkbox will not validate the org credentials when the record is saved or viewed.</inlineHelpText>
        <label>Disable Validation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Metadata_Types__c</fullName>
        <inlineHelpText>Empty means all types. Select one or more types to limit the backup only to selected items.</inlineHelpText>
        <label>Metadata Types</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Oauth_Signature__c</fullName>
        <description>This value is automatically set and updated by Copado.</description>
        <inlineHelpText>This value is automatically set and updated by Copado.</inlineHelpText>
        <label>Oauth Signature</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Org_Type__c</fullName>
        <label>Org Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Production/Developer</fullName>
                    <default>true</default>
                    <label>Production/Developer</label>
                </value>
                <value>
                    <fullName>Sandbox</fullName>
                </value>
                <value>
                    <fullName>Scratch Org - Test only</fullName>
                </value>
                <value>
                    <fullName>Scratch Org</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Validated_Status__c</fullName>
        <formula>IF(ISBLANK(Validated_Date__c),
&quot;Error&quot; ,
 IF( DATEVALUE(Validated_Date__c) == TODAY(), 
    &quot;OK&quot;,&quot;None&quot;) 
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Validated Status</label>
        <type>Text</type>
    </fields>
    <label>Org Credential</label>
    <nameField>
        <label>Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Org Credentials</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/OrgsSelector.cls
public with sharing class OrgsSelector extends fflib_SObjectSelector {
    public SObjectType getSObjectType() {
        return Org__c.sObjectType;
    }

    public List<SObjectField> getSObjectFieldList() {


        return new List<SObjectField>{
            Org__c.Id,
            Org__c.Name,
            Org__c.Metadata_Types__c,
            Org__c.Disable_Validation__c,
            Org__c.Oauth_Signature__c,
            Org__c.Validated_Status__c,
            Org__c.Org_Type__c
        };


    }

    public OrgsSelector() {
        this(true);
    }

    public OrgsSelector(Boolean enforceFLS) {
        super(false, true, enforceFLS);
    }

    public List<Org__c> byId(List<Id> recordIds) {


        return byId(new Set<Id>(recordIds));


    }

    public List<Org__c> byId(Set<Id> recordIds) {
        return (List<Org__c>) selectSObjectsById(recordIds);
    }
}