objects/Project__c.object
<CustomObject>
    <description>Overall object for capturing the project details.</description>
    <fields>
        <fullName>Index_Metadata__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>When this field is checked, Copado will index the metadata selected against the user stories into the User Story Metadata custom object. Indexed metadata can be used for reporting and compliance, and it&apos;s also used by Copado overlap awareness feature.</inlineHelpText>
        <label>Index Metadata</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Planned</fullName>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User_Story__c.object
<CustomObject>
    <description>Agile form of requirements gathering</description>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Project where the User Story belongs.</description>
        <inlineHelpText>Project where the User Story belongs.</inlineHelpText>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Current status of the implementation of the User Story.</description>
        <inlineHelpText>Current status of the implementation of the User Story.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Backlog</fullName>
                </value>
                <value>
                    <fullName>Backburner</fullName>
                </value>
                <value>
                    <fullName>Awaiting Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Ready for testing</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Stop_Indexing_Metadata__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked, the User Story will not be indexed for Copado&apos;s Overlap Awareness.</description>
        <inlineHelpText>If checked, the User Story will not be indexed for Copado&apos;s Overlap Awareness.</inlineHelpText>
        <label>Stop Indexing Metadata</label>
        <type>Checkbox</type>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>User Story Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User_Story_Metadata__c.object
<CustomObject>
    <fields>
        <fullName>Metadata_API_Name__c</fullName>
        <label>Metadata API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Potential Conflict</fullName>
                </value>
                <value>
                    <fullName>Under Review</fullName>
                </value>
                <value>
                    <fullName>Conflict Resolved</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Back Promoted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_Story__c</fullName>
        <label>User Story</label>
        <referenceTo>User_Story__c</referenceTo>
        <relationshipLabel>User Story Metadata</relationshipLabel>
        <relationshipName>User_Story_Metadata</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>User Story Metadata</label>
    <nameField>
        <label>User Story Metadata Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Story Metadata</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/UserStoriesMetadataSelectorTest.cls
@IsTest
public with sharing class UserStoriesMetadataSelectorTest {
    @TestSetup
    private static void makeData() {
        createData();
    }

    @IsTest
    private static void defaultFields() {
        // Exercise
        UserStoriesMetadataSelector selector = new UserStoriesMetadataSelector();
        List<SObjectField> metadataFields = selector.getSObjectFieldList();

        // Verify
        List<SObjectField> assertFields = new List<SObjectField>{
            User_Story_Metadata__c.Id,
            User_Story_Metadata__c.Status__c,
            User_Story_Metadata__c.User_Story__c,
            User_Story_Metadata__c.Metadata_API_Name__c
        };
        System.assertEquals(assertFields, metadataFields, 'Fields returned does not match');
    }

    @IsTest
    private static void queryByIds() {
        // Setup
        Map<Id, User_Story_Metadata__c> metadataById = new Map<Id, User_Story_Metadata__c>(
            [SELECT Id, Status__c, Metadata_API_Name__c, User_Story__c FROM User_Story_Metadata__c LIMIT 2]
        );

        // Exercise
        UserStoriesMetadataSelector selector = new UserStoriesMetadataSelector();
        List<User_Story_Metadata__c> storiesMetadataById = selector.byId(metadataById.keySet());

        // Verify
        System.assertEquals(2, storiesMetadataById.size(), 'Number of records returned should be 2');
        System.assert(metadataById.values().equals(storiesMetadataById), 'Lists must be identical');
    }

    @IsTest
    private static void queryByStoryIdsIndexingEnabled() {
        // Setup
        User_Story__c story = [SELECT Id FROM User_Story__c LIMIT 1];

        // Exercise
        UserStoriesMetadataSelector selector = new UserStoriesMetadataSelector();
        List<User_Story_Metadata__c> storiesIndexinEnabled = selector.byStoryIdsIndexingEnabled(new Set<Id>{ story.Id });

        // Verify
        List<User_Story_Metadata__c> assertList = [
            SELECT Id, Metadata_API_Name__c, Status__c, User_Story__c
            FROM User_Story_Metadata__c
            WHERE User_Story__c = :story.Id AND User_Story__r.Project__r.Index_Metadata__c = TRUE AND User_Story__r.Stop_Indexing_Metadata__c = FALSE
        ];
        System.assertEquals(2, storiesIndexinEnabled.size(), 'Number of records returned should be 2');
        System.assert(assertList.equals(storiesIndexinEnabled), 'Lists must be identical');
    }

    @IsTest
    private static void queryByStoryStatus() {
        // Exercise
        UserStoriesMetadataSelector selector = new UserStoriesMetadataSelector();
        Database.QueryLocator query = selector.byStoryStatus(new Set<Id>(), 'Potential Conflict');

        // Verify
        String assertQuery = 'SELECT Id, Metadata_API_Name__c, Status__c, User_Story__c FROM User_Story_Metadata__c WHERE User_Story__c = :ids AND Status__c = :status ORDER BY Name ASC NULLS FIRST';
        System.assertEquals(assertQuery.trim(), query.getQuery().trim(), 'Query is not correct');
    }

    @IsTest
    private static void queryByMetadataIndexingEnabled() {
        // Exercise
        UserStoriesMetadataSelector selector = new UserStoriesMetadataSelector();
        Database.QueryLocator query = selector.byMetadataIndexingEnabled(new Set<String>());

        // Verify
        String assertQuery = 'SELECT Id, Metadata_API_Name__c, Status__c, User_Story__c FROM User_Story_Metadata__c WHERE Metadata_API_Name__c = :apiNames AND User_Story__r.Project__r.Index_Metadata__c = true AND User_Story__r.Stop_Indexing_Metadata__c = false ORDER BY Name ASC NULLS FIRST';
        System.assertEquals(assertQuery.trim(), query.getQuery().trim(), 'Query is not correct');
    }

    @IsTest
    private static void byMetadatanameStatusIndexingEnabled() {
        // Exercise
        UserStoriesMetadataSelector selector = new UserStoriesMetadataSelector();
        Database.QueryLocator query = selector.byMetadatanameStatusIndexingEnabled(new Set<String>(), 'Potential Conflict');

        // Verify
        String assertQuery = 'SELECT Id, Metadata_API_Name__c, Status__c, User_Story__c FROM User_Story_Metadata__c WHERE Status__c = :status AND Metadata_API_Name__c = :apiNames AND User_Story__r.Project__r.Index_Metadata__c = true AND User_Story__r.Stop_Indexing_Metadata__c = false ORDER BY Name ASC NULLS FIRST';
        System.assertEquals(assertQuery.trim(), query.getQuery().trim(), 'Query is not correct');
    }

    private static void createData() {
        Project__c project = new Project__c(Name = 'My Project', Index_Metadata__c = true);
        insert project;
        User_Story__c story = new User_Story__c(Project__c = project.Id);
        insert story;

        User_Story_Metadata__c metadata1 = new User_Story_Metadata__c(
            Status__c = 'Potential Conflict',
            Metadata_API_Name__c = 'CustomField.Account.Number__c',
            User_Story__c = story.Id
        );

        User_Story_Metadata__c metadata2 = new User_Story_Metadata__c(
            Status__c = 'Potential Conflict',
            Metadata_API_Name__c = 'CustomField.Account.Text__c',
            User_Story__c = story.Id
        );

        insert new List<User_Story_Metadata__c>{ metadata1, metadata2 };
    }
}