objects/Project__c.object
<CustomObject>
    <description>Overall object for capturing the project details.</description>
    <fields>
        <fullName>Index_Metadata__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>When this field is checked, Copado will index the metadata selected against the user stories into the User Story Metadata custom object. Indexed metadata can be used for reporting and compliance, and it&apos;s also used by Copado overlap awareness feature.</inlineHelpText>
        <label>Index Metadata</label>
        <type>Checkbox</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User_Story__c.object
<CustomObject>
    <description>Agile form of requirements gathering</description>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Project where the User Story belongs.</description>
        <inlineHelpText>Project where the User Story belongs.</inlineHelpText>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stop_Indexing_Metadata__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked, the User Story will not be indexed for Copado&apos;s Overlap Awareness.</description>
        <inlineHelpText>If checked, the User Story will not be indexed for Copado&apos;s Overlap Awareness.</inlineHelpText>
        <label>Stop Indexing Metadata</label>
        <type>Checkbox</type>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>User Story Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/UserStoriesSelectorTest.cls
@IsTest
public with sharing class UserStoriesSelectorTest {
    @IsTest
    private static void defaultFields() {
        // Exercise
        UserStoriesSelector selector = new UserStoriesSelector();
        List<SObjectField> metadataFields = selector.getSObjectFieldList();

        // Verify
        List<SObjectField> assertFields = new List<SObjectField>{ User_Story__c.Id };
        System.assertEquals(assertFields, metadataFields, 'Fields returned does not match');
    }

    @IsTest
    private static void queryByIds() {
        // Setup
        User_Story__c story = new User_Story__c();
        insert story;
        
        // Exercise
        List<User_Story__c> storiesById = new UserStoriesSelector().byId(new Set<Id>{ story.Id });

        // Verify
        List<User_Story__c> assertStories = [SELECT Id FROM User_Story__c LIMIT 1];
        System.assertEquals(1, storiesById.size(), 'Number of records returned should be 1');
        System.assert(assertStories.equals(storiesById), 'Lists must be identical');
    }

    @IsTest
    private static void queryByIdWithIndexingEnabled() {
        // Exercise
        UserStoriesSelector selector = new UserStoriesSelector();
        Database.QueryLocator query = selector.byIdWithIndexingEnabled(new Set<Id>());

        // Verify
        String assertQuery = 'SELECT Id FROM User_Story__c WHERE Id IN :ids AND Stop_Indexing_Metadata__c = false AND Project__r.Index_Metadata__c = true ORDER BY Name ASC NULLS FIRST';
        System.assertEquals(assertQuery.trim(), query.getQuery().trim(), 'Query is not correct');
    }

    @IsTest
    private static void queryWithIndexingEnabled() {
        // Exercise
        UserStoriesSelector selector = new UserStoriesSelector();
        Database.QueryLocator query = selector.withIndexingEnabled();

        // Verify
        String assertQuery = 'SELECT Id FROM User_Story__c WHERE Stop_Indexing_Metadata__c = false AND Project__r.Index_Metadata__c = true ORDER BY Name ASC NULLS FIRST';
        System.assertEquals(assertQuery.trim(), query.getQuery().trim(), 'Query is not correct');
    }
}